/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamplesIndexRouteImport } from './routes/examples/index'
import { Route as ExamplesTripsRouteImport } from './routes/examples/trips'
import { Route as ExamplesScatterplotRouteImport } from './routes/examples/scatterplot'
import { Route as ExamplesArcRouteImport } from './routes/examples/arc'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesIndexRoute = ExamplesIndexRouteImport.update({
  id: '/examples/',
  path: '/examples/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesTripsRoute = ExamplesTripsRouteImport.update({
  id: '/examples/trips',
  path: '/examples/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesScatterplotRoute = ExamplesScatterplotRouteImport.update({
  id: '/examples/scatterplot',
  path: '/examples/scatterplot',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesArcRoute = ExamplesArcRouteImport.update({
  id: '/examples/arc',
  path: '/examples/arc',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/examples/arc': typeof ExamplesArcRoute
  '/examples/scatterplot': typeof ExamplesScatterplotRoute
  '/examples/trips': typeof ExamplesTripsRoute
  '/examples/': typeof ExamplesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examples/arc': typeof ExamplesArcRoute
  '/examples/scatterplot': typeof ExamplesScatterplotRoute
  '/examples/trips': typeof ExamplesTripsRoute
  '/examples': typeof ExamplesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/examples/arc': typeof ExamplesArcRoute
  '/examples/scatterplot': typeof ExamplesScatterplotRoute
  '/examples/trips': typeof ExamplesTripsRoute
  '/examples/': typeof ExamplesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/examples/arc'
    | '/examples/scatterplot'
    | '/examples/trips'
    | '/examples/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/examples/arc'
    | '/examples/scatterplot'
    | '/examples/trips'
    | '/examples'
  id:
    | '__root__'
    | '/'
    | '/examples/arc'
    | '/examples/scatterplot'
    | '/examples/trips'
    | '/examples/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamplesArcRoute: typeof ExamplesArcRoute
  ExamplesScatterplotRoute: typeof ExamplesScatterplotRoute
  ExamplesTripsRoute: typeof ExamplesTripsRoute
  ExamplesIndexRoute: typeof ExamplesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/': {
      id: '/examples/'
      path: '/examples'
      fullPath: '/examples/'
      preLoaderRoute: typeof ExamplesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/trips': {
      id: '/examples/trips'
      path: '/examples/trips'
      fullPath: '/examples/trips'
      preLoaderRoute: typeof ExamplesTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/scatterplot': {
      id: '/examples/scatterplot'
      path: '/examples/scatterplot'
      fullPath: '/examples/scatterplot'
      preLoaderRoute: typeof ExamplesScatterplotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/arc': {
      id: '/examples/arc'
      path: '/examples/arc'
      fullPath: '/examples/arc'
      preLoaderRoute: typeof ExamplesArcRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamplesArcRoute: ExamplesArcRoute,
  ExamplesScatterplotRoute: ExamplesScatterplotRoute,
  ExamplesTripsRoute: ExamplesTripsRoute,
  ExamplesIndexRoute: ExamplesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
